config/routes.rb
Bickr::Application.routes.draw do
  resources :locations

  match 'qritems/generate' => 'qritems#generate'
  match 'qritems/tag' => 'qritems#tag'
  match 'qritems/view' => 'qritems#view'
  match '/view/:id' => 'qritems#view'
  
  resources :qritems
  
  

end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :qritem
end

app/models/qritem.rb
class Qritem < ActiveRecord::Base
  has_many :locations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.xml
  def index
    @locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.xml
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.xml
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.xml
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to(@location, :notice => 'Location was successfully created.') }
        format.xml  { render :xml => @location, :status => :created, :location => @location }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @location.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.xml
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to(@location, :notice => 'Location was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @location.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.xml
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to(locations_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/qritems_controller.rb
require "base64"
require 'uri'

class QritemsController < ApplicationController
  # GET /qritems
  # GET /qritems.xml
  def index
    @qritems = Qritem.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @qritems }
    end
  end

  # GET /qritems/1
  # GET /qritems/1.xml
  def show
    @qritem = Qritem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @qritem }
    end
  end

  # GET /qritems/new
  # GET /qritems/new.xml
  def new
    @qritem = Qritem.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @qritem }
    end
  end

  # GET /qritems/1/edit
  def edit
    @qritem = Qritem.find(params[:id])
  end

  # POST /qritems
  # POST /qritems.xml
  def create
    @qritem = Qritem.new(params[:qritem])

    respond_to do |format|
      if @qritem.save
        format.html { redirect_to(@qritem, :notice => 'Qritem was successfully created.') }
        format.xml  { render :xml => @qritem, :status => :created, :location => @qritem }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @qritem.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /qritems/1
  # PUT /qritems/1.xml
  def update
    @qritem = Qritem.find(params[:id])

    respond_to do |format|
      if @qritem.update_attributes(params[:qritem])
        format.html { redirect_to(@qritem, :notice => 'Qritem was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @qritem.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /qritems/1
  # DELETE /qritems/1.xml
  def destroy
    @qritem = Qritem.find(params[:id])
    @qritem.destroy

    respond_to do |format|
      format.html { redirect_to(qritems_url) }
      format.xml  { head :ok }
    end
  end
  
  # GENERATE /qritems/generate
  # Create a new QR item
  def generate
    
    # Create a unique tag name
    entry_count = Qritem.all.size
    @tag = Base64.encode64("X" + entry_count.to_s)
    @tag = @tag.gsub("=", "x")
    
    # Generate URL for unique item
    @tag_url = "http://bickr.heroku.com/view/" + @tag
    
    # Create a QR code url from this tag name using the Google API
    @qr_url = "http://chart.apis.google.com/chart?chs=200x200&cht=qr&chl=" + URI.escape(@tag_url) + "%0A"
    
    # Save this tag
    @new_qr_item = Qritem.new
    @new_qr_item.tag = @tag.strip
    @new_qr_item.url = @qr_url
    @new_qr_item.save
    
  end

  # VIEW /:id
  # View a QR item
  def view    
    params.inspect
    @tag = params[:id].to_s.strip      
    @item = Qritem.find( :first, :conditions => ["tag = '#{@tag}'"] )      
    
  end

  # TAG /update
  # Add a tag to a QRItem
  def tag
    puts "TAG()"
    params.inspect
    
    tag = params[:id].to_s.strip
    name = params[:name].to_s.strip
    comment = params[:comment].to_s.strip
    lat = params[:lat].to_s.strip
    lon = params[:lon].to_s.strip
    
    item = Qritem.find( :first, :conditions => ["tag = '#{tag}'"])
    if item
      location = Location.new
      location.name = name
      location.comment = comment
      location.lat = lat
      location.lon = lon
      location.save
      
      item.locations << location
      item.save
    end  
    
    redirect_to :action => "view", :id => "#{tag}"
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/qritems_helper.rb
module QritemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bickr</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lon %><br />
    <%= f.text_field :lon %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Comment</th>
    <th>Lat</th>
    <th>Lon</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locations.each do |location| %>
  <tr>
    <td><%= location.name %></td>
    <td><%= location.comment %></td>
    <td><%= location.lat %></td>
    <td><%= location.lon %></td>
    <td><%= link_to 'Show', location %></td>
    <td><%= link_to 'Edit', edit_location_path(location) %></td>
    <td><%= link_to 'Destroy', location, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @location.name %>
</p>

<p>
  <b>Comment:</b>
  <%= @location.comment %>
</p>

<p>
  <b>Lat:</b>
  <%= @location.lat %>
</p>

<p>
  <b>Lon:</b>
  <%= @location.lon %>
</p>

<%= @location.inspect %>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/qritems/_form.html.erb
<%= form_for(@qritem) do |f| %>
  <% if @qritem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qritem.errors.count, "error") %> prohibited this qritem from being saved:</h2>

      <ul>
      <% @qritem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tag %><br />
    <%= f.text_field :tag %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/qritems/edit.html.erb
<h1>Editing qritem</h1>

<%= render 'form' %>

<%= link_to 'Show', @qritem %> |
<%= link_to 'Back', qritems_path %>

app/views/qritems/generate.html.erb
You have just created a new Bickr QR Code!<br><br>

Scan this code with any QR code reader and follow the link to use.<br><br>

<image src="<%= @qr_url%>" width="200" height="200" alt="QR Code Image">

app/views/qritems/index.html.erb
<h1>Listing qritems</h1>

<table>
  <tr>
    <th>Tag</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @qritems.each do |qritem| %>
  <tr>
    <td><%= qritem.tag %></td>
    <td><%= qritem.url %></td>
    <td><%= link_to 'Show', qritem %></td>
    <td><%= link_to 'Edit', edit_qritem_path(qritem) %></td>
    <td><%= link_to 'Destroy', qritem, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Qritem', new_qritem_path %>

app/views/qritems/new.html.erb
<h1>New qritem</h1>

<%= render 'form' %>

<%= link_to 'Back', qritems_path %>

app/views/qritems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tag:</b>
  <%= @qritem.tag %>
</p>

<p>
  <b>Url:</b>
  <%= @qritem.url %>
</p>


<%= link_to 'Edit', edit_qritem_path(@qritem) %> |
<%= link_to 'Back', qritems_path %>

app/views/qritems/view.html.erb
<style type="text/css">
.c_rect_main {
	font-family: Georgia, "Times New Roman", Times, serif;
	font-size: 12px;
	background-color: #FFF;
	position: absolute;
	height: 110%;
	width: 95%;
	top: 10px;
	bottom: 10px;
	border: 5px solid #F30;
	margin-left: auto;
	margin-right:auto;
}
.c_rect_title {
	font-family: Georgia, "Times New Roman", Times, serif;
	font-size: 12px;
	position: relative;
	height: 55px;
	width: 98%;
	top: 5px;
	margin-left: auto;
	margin-right: auto;
	background-color: #FFF;
}

.c_rect_post {
	font-family: Georgia, "Times New Roman", Times, serif;
	font-size: 12px;
	background-color: #FFF;
	position: relative;
	width: 98%;
	top: 20px;
	margin-left: auto;
	margin-right: auto;
}
.c_rect_map {
	font-family: Georgia, "Times New Roman", Times, serif;
	font-size: 12px;
	background-color: #FFF;
	position: relative;	
	width: 98%;
	top: 25px;
	margin-right: auto;
	margin-left: auto;
	
}
.c_rect_comments {
	font-family: Georgia, "Times New Roman", Times, serif;
	font-size: 12px;
	background-color: #FFF;
	width: 98%;
	margin-right: auto;
	margin-left: auto;
	position: relative;
	top: 30px;
}
.c_rect_comments_entry {
	font-family: Georgia, "Times New Roman", Times, serif;
	font-size: 12px;
	border-top-width: 2px;
	border-right-width: 2px;
	border-bottom-width: 2px;
	border-left-width: 2px;
	border-top-style: dotted;
	margin-top: 15px;
}

.s_heading_section {
	font-family: Georgia, "Times New Roman", Times, serif;
	font-size: 24px;
	font-weight: bold;
	font-style: italic;
}

.s_link_major {
	font-family: Georgia, "Times New Roman", Times, serif;
	font-size: 18px;
	font-weight: bold;
	font-style: italic;
}

.s_text {
	font-family: Georgia, "Times New Roman", Times, serif;
	font-size: 12px;
}
</style>


<script type="text/javascript" src="http://maps.google.com/maps/api/js?libraries=geometry&sensor=true"></script>

<script type="text/javascript">

  var lat = 0;
  var lon = 0;
  
  //-----------------------------------------------------------
  // Class: Location Tag Type
  //-----------------------------------------------------------
  function BLocationType(name, comment, lat, lon) {
  	this.name = name;
  	this.comment = comment;
  	this.lat = lat;
  	this.lon = lon;
  }
    
  //-----------------------------------------------------------
  // Handle Position Found Callback
  //-----------------------------------------------------------
  function handlePositionFound(position) {
  	document.getElementById("d_current_position").innerHTML = "Latitude: " + position.coords.latitude + "<br>Longitude: " + position.coords.longitude;
  	
  	lat = position.coords.latitude;
  	lon = position.coords.longitude;
  }
  
  //-----------------------------------------------------------
  // Appends Name, Comment, and Location to Current Tag
  //-----------------------------------------------------------
  function registerTag() {
    name = document.getElementById("f_name").value
    comment = document.getElementById("f_comment").value
    
    name = encodeURIComponent( name );
    comment = encodeURIComponent( comment );
    
    window.location = "/qritems/tag?id=<%= @item.tag %>&name=" + name + "&comment=" + comment + "&lat=" + lat + "&lon=" + lon    
  }
  
  // Google Maps Global Variables
  var gMap = null;
  
  // Generate Lat/Lon Array
  var gMapPointCount = <%= @item.locations.size %>;
  var gMapPoints = new Array
  						( 
  							<% @item.locations.each do |location| %>
  							  <%= "new BLocationType( '#{location.name}', '#{location.comment}', #{location.lat}, #{location.lon} )" %>,
  							<% end %>
  							new Array( 0, 0 )
  						);
  var gMarkers = new Array();
  var gInfoWindows = new Array();
  
  //-----------------------------------------------------------
  // Initialize Google Maps
  //-----------------------------------------------------------
  function initializeGoogleMaps() {  	
    if( gMapPointCount > 0 ) {
	    
	    // Configure Map Options
	  	var myLatlng = new google.maps.LatLng(gMapPoints[0].lat, gMapPoints[0].lon);
	    var mapOptions = {
	    	zoom: 12,
	    	center: myLatlng,
	    	mapTypeId: google.maps.MapTypeId.ROADMAP    
	    }
	    
	    // Create New Map
	  	gMap = new google.maps.Map(document.getElementById("d_map"), mapOptions);
	  	
	  	// Add Map Points
	  	for(i = 0; i < gMapPointCount; i++) {
	  		var markerLatLon = new google.maps.LatLng(gMapPoints[i].lat, gMapPoints[i].lon);

			gInfoWindows[i] = new google.maps.InfoWindow({
				content: gMapPoints[i].name
				});
				
 	  		gMarkers[i] = new google.maps.Marker({
	  			position: markerLatLon,
	  			map: gMap,
	  			title: gMapPoints[i].name
 	  			});
 	  		
 	  		google.maps.event.addListener(gMarkers[i], 'click', makeMarkerCenterEvent(gMap, gMarkers[i], gInfoWindows[i]) );
	  	}
	} else {
		document.getElementById("d_map").innerHTML = "This tag has not been geotagged!";
	}	
  }

  //-----------------------------------------------------------
  // Event Factory for Marker Center Event
  //-----------------------------------------------------------
  function makeMarkerCenterEvent(map, marker, infoWindow) {
  	return function() {
		map.setCenter(marker.position);
  	}
  }
  
  //-----------------------------------------------------------
  // Load Google Maps
  //-----------------------------------------------------------
  function loadGoogleMaps() {
  	var script = document.createElement("script");
  	script.type = "text/javascript";
  	script.src = "http://maps.google.com/maps/api/js?sensor=false&callback=initializeGoogleMaps";
  	document.body.appendChild(script);
  }
  
  window.onload = loadGoogleMaps();
  
</script>


<div class="c_rect_main" id="d_rect_main">
  <div class="c_rect_title" id="d_rect_title">
  <img src="/images/bickr_logo.jpg" width="200" height="55" /></div>
  <div class="c_rect_post" id="d_rect_post">
  	<span class="s_heading_section">POST</span>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr><td class="s_text">Name:</td><td><input id="f_name" type="text" class="s_text"></td></tr>
  <tr><td class="s_text">Comment:</td><td><input id="f_comment" type="text" class="s_text"></td></tr>
  <tr><td class="s_text">Location:</td><td class="s_text"><div id="d_current_position">Loading Location...</div></td></tr>
  <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
  <tr><td>&nbsp;</td><td class="s_link_major"><a onclick="javascript:registerTag()">Add Comment</a></td></tr>
  </tr>
</table>
  
  </div>
  <div class="c_rect_map" id="d_rect_map"><div id="d_map" style="width:100%; height:300px"></div></div>
  
  <div class="c_rect_comments" id="d_rect_comments">
  	<span class="s_heading_section">Tag History</span><br />
  	
	<% location_idx = 1 %>
	<% if @item.locations.size == 0 %>
	This tag has not been geotagged.
	<% end %>
	<% @item.locations.each do |location| %>
	  
	  	<div class="c_rect_comments_entry">
	    <%= location.name %> - <%= location.created_at %><br />
	    <%= location.comment %>
	    </div>

	<% end %>

  </div>
  
  
</div>

<script type="text/javascript">
  navigator.geolocation.getCurrentPosition(handlePositionFound);
</script>